# Generated by Django 5.0.6 on 2025-05-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.company'),
        ),
        migrations.AddField(
            model_name='faq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='users.company'),
        ),
        migrations.AddField(
            model_name='integration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='users.company'),
        ),
        migrations.AddField(
            model_name='message',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.company'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.client'),
        ),
        migrations.AddField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='users.company'),
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('company', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together={('company', 'category', 'title')},
        ),
    ]
